#!/bin/bash

help(){
    echo "Usage: "
    echo "  kubectl ansible-playbook [options]"
    echo ""
    options
}

options(){
    cat <<"EOF"
Options:
  -h, --help                      Show this message
Example:
  Scenario1 - Run playbook on Kubernetes Pods in the given namespace
  $ kubectl ansible-playbook -i ~/inventory_k8s.yml main.yml --limit namespace_test_pods -v
EOF
}

plugin_main() {
  while [ $# -gt 0 ] ; do
    case $1 in
      "-h" | "--help")
        help
        exit 0
        ;;
      *)
        help >&2
        exit 1
        ;;
    esac
  done

  if [[ "$(type kubectl &>/dev/null; echo $?)" -eq 1 ]]; then
    echo "Error: missing kubectl command" >&2
    echo "Please install kubectl (https://kubernetes.io/docs/tasks/tools/install-kubectl/)" >&2
    exit 1
  fi

}

plugin_main "$@"